### ISSUE TITLE
[FEAT] 합동세미나 마무리 작업

### ISSUE THREAD

**Issue by hansh0101** [THE-SOPT-30th-DaangnMarket-14/Daangn-Android#19]
## 📌  Feature Issue

[FEAT] 합동세미나 마무리 작업

## 📝  To-do

- [x] 화면 전환 구현
- [x] 화면 전환 후 새로고침 구현
- [x] 각종 중복 파일, 미사용 파일 제거
