### ISSUE TITLE
[FEAT] 글쓰기 뷰 구현

### ISSUE THREAD

**Issue by uxri** [THE-SOPT-30th-DaangnMarket-14/Daangn-Android#2]
## 📌  Feature Issue
판매 내용을 판매글로 작성하여 업로드하는 기능 구현

## 📝  To-do
- [x] 전체 뷰 스크롤링 (상단 상태바, 키보드 고정)
- [x] 제목 제한 15자, 가격 제한 10자, 내용 제한 1000자
- [x] 키보드 올라온 상태에서 여백 선택 시 키보드 내려감
- [x] 가격 텍스트필드 숫자 키패드로 디폴트
- [x] 키보드와 입력창 사이 간격 최소 40
- [ ] 내용 모두 입력 시 완료 버튼 활성화
