### ISSUE TITLE
[FIX] ImagePicker 수정

### ISSUE THREAD

**Issue by hansh0101** [THE-SOPT-30th-DaangnMarket-14/Daangn-Android#7]
## 📌  Feature Issue

[FIX] ImagePicker 수정 및 부족한 점 보완

## 📝  To-do

- [x] ImagePicker 확인 클릭 시에만 선택된 이미지들이 반영되게 하기
- [x] 카메라로 찍은 사진 Upload 할 수 있도록 구현하기
- [x] 대표사진 설정하기
- [x] 작성하기 뷰 UI 일부 수정
